# Generated by Django 4.2.29 on 2026-03-24 03:34

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django
import pgvector.django.vector
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cache', '0001_initial'),
        ('users', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(db_index=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('module_context', models.TextField(blank=True, null=True)),
                ('is_summarized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='courses.course')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='users.user')),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'session_id', 'created_at'], name='conv_user_session')],
            },
        ),
    ]
