# Generated by Django 4.2.29 on 2026-03-24 03:34

from django.db import migrations, models
import pgvector.django
import pgvector.django.vector
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='QueryCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('query_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('response', models.TextField()),
                ('hit_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'query_cache',
                'ordering': ['-created_at'],
            },
        ),
    ]
