# Generated by Django 4.2.29 on 2026-03-24 03:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.IntegerField()),
                ('problems', models.JSONField(default=list)),
                ('total_problems', models.IntegerField(default=2)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coding_tests',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('topic', models.TextField()),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration_weeks', models.IntegerField(blank=True, null=True)),
                ('hours_per_day', models.IntegerField(blank=True, null=True)),
                ('goals', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('generating', 'Generating')], default='active', max_length=20)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generation_progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.user')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeekPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.IntegerField()),
                ('theme', models.TextField(blank=True, null=True)),
                ('objectives', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('is_completed', models.BooleanField(default=False)),
                ('test_generated', models.BooleanField(default=False)),
                ('test_unlocked', models.BooleanField(default=False)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='courses.course')),
            ],
            options={
                'db_table': 'week_plans',
                'ordering': ['week_number'],
                'unique_together': {('course', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyTestAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.IntegerField()),
                ('answers', models.JSONField(default=dict)),
                ('score', models.IntegerField()),
                ('total', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('passed', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='weekly_test_attempts', to='courses.course')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='weekly_test_attempts', to='users.user')),
            ],
            options={
                'db_table': 'weekly_test_attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='CodingTestAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submissions', models.JSONField(default=dict)),
                ('score', models.IntegerField()),
                ('total', models.IntegerField(default=2)),
                ('percentage', models.FloatField()),
                ('passed', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('coding_test', models.ForeignKey(db_column='coding_test_id', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.codingtest')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='coding_test_attempts', to='users.user')),
            ],
            options={
                'db_table': 'coding_test_attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddField(
            model_name='codingtest',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='coding_tests', to='courses.course'),
        ),
        migrations.CreateModel(
            name='WeeklyTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.IntegerField()),
                ('questions', models.JSONField(default=list)),
                ('total_questions', models.IntegerField(default=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='weekly_tests', to='courses.course')),
            ],
            options={
                'db_table': 'weekly_tests',
                'unique_together': {('course', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField()),
                ('title', models.TextField(blank=True, null=True)),
                ('tasks', models.JSONField(blank=True, default=dict)),
                ('theory_content', models.TextField(blank=True, default='')),
                ('code_content', models.TextField(blank=True, default='')),
                ('quiz_raw', models.TextField(blank=True, default='')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=True)),
                ('theory_generated', models.BooleanField(default=False)),
                ('code_generated', models.BooleanField(default=False)),
                ('quiz_generated', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('quiz_score', models.FloatField(blank=True, null=True)),
                ('quiz_attempts', models.IntegerField(default=0)),
                ('week_plan', models.ForeignKey(db_column='week_plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='days', to='courses.weekplan')),
            ],
            options={
                'db_table': 'day_plans',
                'ordering': ['day_number'],
                'unique_together': {('week_plan', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_days', models.IntegerField(default=0)),
                ('completed_days', models.IntegerField(default=0)),
                ('total_weeks', models.IntegerField(default=0)),
                ('completed_weeks', models.IntegerField(default=0)),
                ('current_week', models.IntegerField(default=1)),
                ('current_day', models.IntegerField(default=1)),
                ('overall_percentage', models.FloatField(default=0.0)),
                ('avg_quiz_score', models.FloatField(default=0.0)),
                ('avg_test_score', models.FloatField(default=0.0)),
                ('total_study_time', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.course')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='users.user')),
            ],
            options={
                'db_table': 'course_progress',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='codingtest',
            unique_together={('course', 'week_number')},
        ),
    ]
