# Generated by Django 4.2 on 2026-03-26 17:30

from django.db import migrations, models
import uuid
import django.core.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('hard', 'Hard'), ('medium', 'Medium')], default='medium', max_length=20)),
                ('time_limit', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)])),
                ('challenges', models.JSONField(default=list)),
                ('total_challenges', models.IntegerField(default=3)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=models.deletion.CASCADE, related_name='coding_tests', to='courses.course')),
            ],
            options={
                'db_table': 'coding_tests',
                'unique_together': {('course', 'week_number')},
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='CodingTestAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.IntegerField()),
                ('answers', models.JSONField(default=dict)),
                ('score', models.IntegerField(default=0)),
                ('total_challenges', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.IntegerField(default=0)),
                ('challenge_results', models.JSONField(default=list)),
                ('coding_test', models.ForeignKey(db_column='coding_test_id', on_delete=models.deletion.CASCADE, related_name='attempts', to='courses.codingtest')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=models.deletion.CASCADE, related_name='coding_test_attempts', to='users.user')),
            ],
            options={
                'db_table': 'coding_test_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_code', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('judge0_token', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('compilation_error', 'Compilation Error'), ('internal_error', 'Internal Error'), ('runtime_error', 'Runtime Error'), ('submitted', 'Submitted'), ('timeout', 'Timeout'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('wrong_answer', 'Wrong Answer')], max_length=50)),
                ('stdout', models.TextField(blank=True, null=True)),
                ('stderr', models.TextField(blank=True, null=True)),
                ('compile_output', models.TextField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('memory_used', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coding_test_attempt', models.ForeignKey(blank=True, db_column='coding_test_attempt_id', null=True, on_delete=models.deletion.CASCADE, related_name='executions', to='courses.codingtestattempt')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=models.deletion.CASCADE, related_name='code_executions', to='users.user')),
            ],
            options={
                'db_table': 'code_executions',
                'ordering': ['-created_at'],
            },
        ),
    ]
