# Generated by Django 4.2 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coding_test_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Optional user-provided course description/requirements', null=True),
        ),
    ]
