# Generated by Django 4.2.29 on 2026-03-24 03:34

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django
import pgvector.django.vector
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cache', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('doc_type', models.TextField(blank=True, null=True)),
                ('topic', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('chunk_index', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(default=0)),
                ('dense_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.document')),
                ('parent_chunk', models.ForeignKey(blank=True, db_column='parent_chunk_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='rag.chunk')),
            ],
            options={
                'db_table': 'chunks',
                'ordering': ['chunk_index'],
            },
        ),
    ]
